# Generated by Django 6.0.3 on 2026-03-11 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='credit',
            new_name='credits_cre_tenant__4a5905_idx',
            old_name='credits_cre_tenant__8b3c7c_idx',
        ),
        migrations.RenameIndex(
            model_name='credit',
            new_name='credits_cre_tenant__cfeeb5_idx',
            old_name='credits_cre_tenant__f6b4e2_idx',
        ),
    ]
