# Generated by Django 6.0.3 on 2026-03-08 21:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('title', models.CharField(default='Meeting', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('scheduled_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Scheduled Meeting',
                'verbose_name_plural': 'Scheduled Meetings',
                'ordering': ['-scheduled_time'],
            },
        ),
    ]
