# Generated by Django 6.0.3 on 2026-03-08 21:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_sid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('from_number', models.CharField(db_index=True, max_length=20)),
                ('to_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('incoming', 'Incoming'), ('forwarded', 'Forwarded to Primary'), ('vapi', 'Forwarded to Vapi AI'), ('completed', 'Completed'), ('failed', 'Failed'), ('no_answer', 'No Answer'), ('busy', 'Busy')], default='incoming', max_length=20)),
                ('duration', models.IntegerField(default=0, help_text='Call duration in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Call Log',
                'verbose_name_plural': 'Call Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
