# Generated by Django 6.0.3 on 2026-03-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_calllog_tenant_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='credits_spent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Credits spent for this call', max_digits=10),
        ),
    ]
